title: About Me
author: Harrison Wong
email: your-email@domain.com
description: 

# social links
instagram_username: harrisonmwong

theme: jekyll-theme-slate
show_excerpts: true # set to false to remove excerpts on the homepage
