title: About Me
author: Harrison Wong
email: your-email@domain.com
description: 3 things I'm Proud of: I passed Cisnero's class, I passed Mr. Cohen's class, I finished 11th grade

# social links
instagram_username: harrisonmwong

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
