title: About Me
author: Harrison Wong
email: your-email@domain.com
description: 3 things I'm Proud of: I passed eleventh grade, I passed first grade, I passed mr cohen class

# social links
instagram_username: harrisonmwong

theme: jekyll-theme-slate
show_excerpts: true # set to false to remove excerpts on the homepage
